name: Commit alert

on:
  push:
    branches:
      - main

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar el ambiente
        run: echo "Setting the environment"

      - name: Send alert
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "I am a simple echo message from a workflow"
